# Generated by Django 4.1.13 on 2024-06-21 22:51

from django.db import migrations, models
import djongo.models.fields
import hero.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('tconst', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('titleType', models.CharField(max_length=500)),
                ('primaryTitle', models.CharField(max_length=500)),
                ('originalTitle', models.CharField(max_length=500)),
                ('isAdult', models.BooleanField()),
                ('startYear', models.CharField(max_length=4)),
                ('endYear', models.CharField(max_length=4)),
                ('runtimeMinutes', models.CharField(max_length=4)),
                ('genres', djongo.models.fields.ArrayField(model_container=hero.models.Genres)),
            ],
        ),
    ]
