# Generated by Django 4.1.13 on 2024-06-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='titles',
            table='titles',
        ),
    ]
